// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/ai" | "/dashboard/ai-tests" | "/dashboard/analytics" | "/dashboard/audit" | "/dashboard/batches" | "/dashboard/candidates" | "/dashboard/exams" | "/dashboard/guide" | "/dashboard/institutes" | "/dashboard/materials" | "/dashboard/monitoring" | "/dashboard/permissions" | "/dashboard/questions" | "/dashboard/results" | "/dashboard/settings" | "/dashboard/setup" | "/dashboard/syllabus" | "/dashboard/teacher" | "/dashboard/users" | "/exam/instructions/[examId]" | "/exam/start/[examId]" | "/help" | "/login" | "/mfa" | "/my-exams" | "/register" | "/verify/certificate/[id]"
type AppRouteHandlerRoutes = "/api/auth/refresh" | "/api/auth/session" | "/api/auth/ws-token" | "/api/v1/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/refresh": {}
  "/api/auth/session": {}
  "/api/auth/ws-token": {}
  "/api/v1/[...path]": { "path": string[]; }
  "/dashboard": {}
  "/dashboard/ai": {}
  "/dashboard/ai-tests": {}
  "/dashboard/analytics": {}
  "/dashboard/audit": {}
  "/dashboard/batches": {}
  "/dashboard/candidates": {}
  "/dashboard/exams": {}
  "/dashboard/guide": {}
  "/dashboard/institutes": {}
  "/dashboard/materials": {}
  "/dashboard/monitoring": {}
  "/dashboard/permissions": {}
  "/dashboard/questions": {}
  "/dashboard/results": {}
  "/dashboard/settings": {}
  "/dashboard/setup": {}
  "/dashboard/syllabus": {}
  "/dashboard/teacher": {}
  "/dashboard/users": {}
  "/exam/instructions/[examId]": { "examId": string; }
  "/exam/start/[examId]": { "examId": string; }
  "/help": {}
  "/login": {}
  "/mfa": {}
  "/my-exams": {}
  "/register": {}
  "/verify/certificate/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
